### ISSUE TITLE
Use bon for code generator

### ISSUE THREAD

**Issue by andrzejressel** [andrzejressel/pulumi-wasm#288]
Should be optional thought - I'm still not sure about it ...

https://github.com/elastio/bon

**Comment by Veetaha** [comment]
Hi, I found this link to `bon` on the web. @andrzejressel could you elaborate what makes you unsure about using `bon`? Maybe something in its design or is it something else?

**Comment by andrzejressel** [comment]
My main issue was with completely unreadable errors when fields was missing, but from what I've seen it was fixed.

**Comment by Veetaha** [comment]
Yep, with the version 2.1 ([blog post](https://elastio.github.io/bon/blog/bon-builder-v2-1-release#better-error-messages)) that problem is fixed. If you have any other things that could block you from adopting `bon`, I'd be happy to hear about them here on in the issues in the [`bon` repo](https://github.com/elastio/bon).

Among the current limitations of `bon` that you should be aware of is the lack of support for conditional compilation with `cfg/cfg_attr` (https://github.com/elastio/bon/issues/68). I'm already working on fixing that for the next `bon` release
